# Generated by Django 5.2.5 on 2025-08-28 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CensusCounty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county_no", models.CharField(max_length=25)),
                ("county_name", models.CharField(max_length=50)),
                ("year", models.IntegerField()),
                ("total_population", models.IntegerField()),
                ("total_houses", models.IntegerField()),
                ("home_ownership_rate", models.FloatField()),
                ("poverty_rate", models.FloatField()),
                ("unemployment_rate", models.FloatField()),
                ("median_age", models.FloatField()),
                ("bachelors_or_higher_degree_pct", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CensusState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_no", models.CharField(max_length=25)),
                ("state_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CensusDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("male_population", models.IntegerField()),
                ("female_population", models.IntegerField()),
                ("white_alone_pct", models.FloatField()),
                ("black_alone_pct", models.FloatField()),
                ("asian_alone_pct", models.FloatField()),
                ("hispanic_latino_pct", models.FloatField()),
                ("foreign_born_pct", models.FloatField()),
                ("non_english_home_pct", models.FloatField()),
                ("avg_household_size", models.FloatField()),
                ("avg_family_size", models.FloatField()),
                ("married_couple_families_pct", models.FloatField()),
                ("single_parent_families_pct", models.FloatField()),
                ("hs_or_higher_pct", models.FloatField()),
                ("renter_occupied_pct", models.FloatField()),
                ("median_year_built", models.IntegerField()),
                ("median_home_value", models.FloatField()),
                ("median_gross_rent", models.IntegerField()),
                ("median_owner_costs_mortgage", models.IntegerField()),
                ("median_household_income", models.IntegerField()),
                ("workers_public_transport_pct", models.FloatField()),
                ("workers_car_pct", models.FloatField()),
                ("workers_bike_pct", models.FloatField()),
                ("health_insurance_coverage_pct", models.FloatField()),
                ("disability_pct", models.FloatField()),
                (
                    "county",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="census.censuscounty",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="censuscounty",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="census.censusstate"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="censuscounty",
            unique_together={("state", "county_no", "year")},
        ),
    ]
