# Generated by Django 5.2.5 on 2025-08-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="censusdetail",
            old_name="median_home_value",
            new_name="median_rooms",
        ),
    ]
