# Generated by Django 5.2.5 on 2025-08-28 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0002_rename_median_home_value_censusdetail_median_rooms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="censusdetail",
            old_name="workers_bike_pct",
            new_name="workers_home_pct",
        ),
    ]
