# Generated by Django 5.2.5 on 2025-08-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0004_alter_censuscounty_bachelors_or_higher_degree_pct_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CensusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("started_at", models.DateTimeField(auto_now=True)),
                ("finish_at", models.DateTimeField(blank=True, null=True)),
                ("log_message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "InProgress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        max_length=30,
                    ),
                ),
            ],
        ),
    ]
