# Generated by Django 5.2.5 on 2025-08-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0005_censuslog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="censuslog",
            name="log_message",
        ),
        migrations.AddField(
            model_name="censuslog",
            name="log_error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="censuslog",
            name="task_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="censuslog",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="censuslog",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "InProgress"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                max_length=30,
            ),
        ),
    ]
