# Generated by Django 5.2.5 on 2025-08-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0006_remove_censuslog_log_message_censuslog_log_error_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censuslog",
            name="task_id",
            field=models.CharField(max_length=30),
        ),
    ]
