# Generated by Django 5.2.5 on 2025-09-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0007_alter_censuslog_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censuslog",
            name="task_id",
            field=models.UUIDField(),
        ),
    ]
