# Generated by Django 5.2.5 on 2025-09-03 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0009_alter_censuslog_task_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censuscounty",
            name="county_no",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
