# Generated by Django 5.2.5 on 2025-09-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0010_alter_censuscounty_county_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censusstate",
            name="state_no",
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
