# Generated by Django 5.2.5 on 2025-09-03 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0011_alter_censusstate_state_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censuscounty",
            name="county_no",
            field=models.CharField(max_length=25),
        ),
    ]
