# Generated by Django 5.2.5 on 2025-09-04 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0012_alter_censuscounty_county_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censusdetail",
            name="county",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detail",
                to="census.censuscounty",
            ),
        ),
    ]
